"""Stable error codes for protocol validation."""

from __future__ import annotations

E_SCHEMA_MISSING_FIELD = "E_SCHEMA_MISSING_FIELD"
E_SCHEMA_INVALID_ENUM = "E_SCHEMA_INVALID_ENUM"
E_SCHEMA_INVALID_FORMAT = "E_SCHEMA_INVALID_FORMAT"
E_REVIEW_EVIDENCE_MISSING = "E_REVIEW_EVIDENCE_MISSING"
E_REVIEW_GATE_INCONSISTENT = "E_REVIEW_GATE_INCONSISTENT"
E_PROTOCOL_RETRY_EXCEEDED = "E_PROTOCOL_RETRY_EXCEEDED"
